### PR TITLE
SwiftPM support

### PR DESCRIPTION
**Pull request by Foboz**
Hey guys, this pull request will allow to integrate your framework by using SwiftPM. Also it doesn't require to run script to strip unused archs. This solution just re-packs existing compiled framework into `.xcframework` (for details please check `build.sh` script).
If you interesting into improvements, please check related topics:
- https://github.com/bielikb/xcframeworks
- https://pspdfkit.com/blog/2020/supporting-xcframeworks/
- https://pspdfkit.com/guides/ios/current/faq/bitcode/ 
- https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages

And extra example of 'how to build `.xcframework` from sources':
- https://github.com/MyEtherWallet/bls-eth-swift/tree/main/bls_framework

### CODE REVIEW

**Comment by yoxisem544** [comment]
I've tried using branch `Foboz:swiftpm-local` to install Lokalise, but I got this error while building:

```
bash: /Users/xxxxx/Library/Developer/Xcode/DerivedData/idjwoqjd-fxlqtqzmnhngzxfbsamacusjvzds/Build/Products/Release-iphonesimulator/idjwoqjd.app/Frameworks/Lokalise.framework/strip-frameworks.sh: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
```

Previously, I use cocoapods to install and run it on apple silicon. Excluding arm64 arch keep causing build to fail.

**Comment by Foboz** [comment]
@yoxisem544 you need to skip step about "Add Run Script" from "Manual install". If you have one - you need to remove it

**Comment by yoxisem544** [comment]
@Foboz I remove the script and it works! I can now install Lokalise via spm! Thanks!

**Comment by yoxisem544** [comment]
@Foboz another question here, have you ever encounter this problem?
After installing via spm, when importing Lokaise, it says "no such module "Lokalise"".

截圖 2021-01-29 下午4 57 28

**Comment by Foboz** [comment]
@yoxisem544, sometimes that error might happens for SwiftPM, but in 99.9% cases build & clean helps. If error still there, then without build target and target arch can't say anything.

**Comment by kristohear** [comment]
@Foboz hey, I see your XCFramework has only intel based simulator architecture. Is it possible to add arm-64 also, to support arm64 MacBooks.

**Comment by TheiOSDude** [comment]
@Foboz Can you seek to support arm-64? 
And equally @Fedya-L when do you vision we can have full SPM support from you guys by merging this PR in?

**Comment by yoxisem544** [comment]
Same problem here, SPM does not support arm64 simulator.

**Comment by Foboz** [comment]
I updated Package.swift since Lokalise team uploaded .xcframework version, so we can use it now. 

@kristohear, @TheiOSDude, @yoxisem544 also as far as I can see their version have m1 support (can't test it in full, I'm still sitting on Intel-based machine and waiting for iMac release)

**Comment by darko55555** [comment]
Do we know when is this going to master branch ?

**Review by darko55555 — APPROVED** [review]

**Comment by yoxisem544** [comment]
It seems its still not working on M1, keep getting error.

**Comment by Fedya-L** [comment]
Hello guys,

Sorry for the long delays and lack of communication on this matter.

We've added Swift Package Manager support, so I will be closing this PR.

@Foboz, thank you for making the PR, it did speed up initial setup/testing process.

@yoxisem544, we tested our .xcframeworks on M1 and did not encounter any issues. Please provide more details on the error message you are getting trough our support system (available on https://app.lokalise.com).

**Comment by yoxisem544** [comment]
I use the version from the one @Fedya-L you provided. The error seems does not appear again! Thanks!

**Pull request closed without merging**
