### PR TITLE
Use XCFramework in the Pod

### PR DESCRIPTION
**Pull request by axelguilmin**
Hello here, 

Our team is using Lokalise OTA on iOS with Cocoapods.
So far this Pod is based on the Universal Framework and we can see in the podspec that **arm64 architecture is excluded**.
This is a big issue for us as we want to stop using Rosetta on our M1 macs and keep the possibility to build on simulators.
I noticed you already published a XCFramework for manual integration, so in this PR I did 2 things : 
- Add the .xcframework to the repository so it's available to Cocoapods (as-is from the [Zip archive](https://github.com/lokalise/lokalise-ios-framework/releases/download/0.10.2/Lokalise.xcframework.0.10.2.zip))
- Update `Lokalise.podspec` to use it

I tried it on my side by putting this in podfile : 

>   pod 'Lokalise', git: 'git@github.com:axelguilmin/lokalise-ios-framework.git'

As far as I can tell it works on Xcode 14.2 and 14.3, M1 Pro and Intel macs

### CODE REVIEW

**Comment by JeanAzzopardi** [comment]
We've run into this exact issue.

**Comment by trszdev** [comment]
+1, tried [axelguilmin](https://github.com/axelguilmin)'s fork, didn't have any problems with it

**Comment by GrigoryUlanov** [comment]
+1

**Comment by axelguilmin** [comment]
This has been solved in version 1.0.0, thank to https://github.com/lokalise/lokalise-ios-framework/pull/22
Closing 👍

**Pull request closed without merging**
